language: rust
sudo: required
dist: trusty
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
rust:
  - nightly
  - stable
before_install:
  - sudo add-apt-repository -y ppa:gnome3-team/gnome3
  - sudo add-apt-repository -y ppa:gnome3-team/gnome3-staging
  - sudo apt-get update
install:
  - sudo apt-get install -y gtk+3.0 libgtk-3-dev
script:
  - rustc --version
  - cargo test --no-default-features
  - cargo build --no-default-features
