language: rust
sudo: false
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
rust:
  - nightly
  - stable

addons:
  apt:
    packages:
      - libgtk-3-dev

env:
  - PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
before_script:
  - ./install_gtk.sh
cache:
  directories:
  - $HOME/local
script:
  - rustc --version
  - cargo test
  - cargo build
